# Generated by Django 5.1.6 on 2025-02-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='input_image_urls',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='output_image_urls',
            field=models.TextField(blank=True, null=True),
        ),
    ]
